class TCM_PROTOCOL(object):
    class MSG_TYPE:
        MSG_TYPE_TO_TCM_REQUEST = 0x0
        MSG_TYPE_TO_TCM_SERVICE = 0x1
        MSG_TYPE_TO_TCM_STICKS = 0x2
        MSG_TYPE_FROM_TCM_PID = 0x3
        MSG_TYPE_FROM_TCM_CL_MATRIX = 0x4
        MSG_TYPE_FROM_TCM_HEART_BEAT = 0x5
        MSG_TYPE_FROM_TCM_SERVICE_CONFIRM = 0x6
        MSG_TYPE_FROM_TCM_TELEMETRY = 0x7

    class MSG_SERVICE_SPECIFIC:
        MSG_SERVICE_ENTER = 0x0
        MSG_SERVICE_REBOOT = 0x1
        MSG_SERVICE_UPDATE_CL_MATRIX = 0x2
        MSG_SERVICE_ENABLE_DIRECT_MOTORS_CTRL = 0x3
        MSG_SERVICE_DISABLE_DIRECT_MOTORS_CTRL = 0x4
        MSG_SERVICE_DIRECT_ACTUATORS_CTRL = 0x5
        MSG_SERVICE_DIRECT_MATRIX_ACTUATORS_CTRL = 0x6
        MSG_SERVICE_SAVE_SETTINGS = 0x7
        MSG_SERVICE_LOAD_SETTINGS = 0x8
        MSG_SERVICE_NEW_PIDS = 0x9
        pass

    class MSG_REQUEST_SPECIFIC:
        MSG_REQUEST_PID = 0x0
        MSG_REQUEST_CL_MATRIX = 0x1
